/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.elinext.task;

import com.elinext.task.data.SampleService;
import com.elinext.task.data.impl.SampleServiceImpl;
import com.elinext.task.injector.Injector;
import com.elinext.task.injector.impl.InjectorImpl;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void sample(){
        Injector injector = new InjectorImpl();

        injector.bind(SampleService.class, SampleServiceImpl.class);


    }
}
